services:
  - type: web
    name: swasthya-setu
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXTAUTH_URL
        value: https://swasthya-setu.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true

